repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: remove-env-entries
      name: Remove sensitive entries from .env
      entry: bash -c 'sed -i "/^PRIVATE_MQTT_BROKER_URL=/d; /^PRIVATE_MQTT_USERNAME=/d; /^PRIVATE_MQTT_PASSWORD=/d" .env'
      language: system
      files: ^\.env$
      stages: [push]
