version: '3.8'
services:
  '0':
    build:
      context: .
      dockerfile: ./src/docker/top_node/Dockerfile
    container_name: 0_container
    environment:
    - VTN_NAME=vtn_0
    - VTN_URL=http://localhost:8080/0/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0
    - GRADIO_PORT=7862
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5000
    - VTN_PORT=8080
    - VTN_SELF_HOST=http://172.18.0.2
    - LAYER=0
    ports:
    - '8080:8080'
    - '7862:7862'
    - '5000:5000'
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    depends_on: {}
    expose:
    - 8080
    - 5000
    healthcheck:
      test: 'curl -f -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8080/0/OpenADR2/Simple/2.0b
        | grep 404 || exit 1'
      interval: 30s
      timeout: 10s
      retries: 10
  '0_0':
    build:
      context: .
      dockerfile: ./src/docker/middle_node/Dockerfile
    container_name: 0_0_container
    environment:
    - VTN_NAME=vtn_0_0
    - VTN_URL=http://localhost:8081/0/0/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/0/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_0
    - GRADIO_PORT=7863
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5001
    - VTN_PORT=8081
    - VTN_SELF_HOST=http://172.18.0.3
    - LAYER=1
    - CONNECT_VTN_URL=http://172.18.0.2:8080/0/OpenADR2/Simple/2.0b
    ports:
    - '8081:8081'
    - '7863:7863'
    - '5001:5001'
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    depends_on:
      '0':
        condition: service_healthy
    expose:
    - 8081
    - 5001
    healthcheck:
      test: 'curl -f -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8081/0/0/OpenADR2/Simple/2.0b
        | grep 404 || exit 1'
      interval: 30s
      timeout: 10s
      retries: 10
  '0_0_0':
    build:
      context: .
      dockerfile: ./src/docker/bottom_node/Dockerfile
    container_name: 0_0_0_container
    environment:
    - VTN_NAME=vtn_0_0_0
    - VTN_URL=http://localhost:8082/0/0/0/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/0/0/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_0_0
    - GRADIO_PORT=7864
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5002
    - VTN_PORT=8082
    - VTN_SELF_HOST=http://172.18.0.4
    - LAYER=2
    - CONNECT_VTN_URL=http://172.18.0.3:8081/0/0/OpenADR2/Simple/2.0b
    ports:
    - '8082:8082'
    - '7864:7864'
    - '5002:5002'
    networks:
      my_network:
        ipv4_address: 172.18.0.4
    depends_on:
      '0_0':
        condition: service_healthy
    expose:
    - 8082
    - 5002
  '0_0_1':
    build:
      context: .
      dockerfile: ./src/docker/bottom_node/Dockerfile
    container_name: 0_0_1_container
    environment:
    - VTN_NAME=vtn_0_0_1
    - VTN_URL=http://localhost:8083/0/0/1/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/0/1/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_0_1
    - GRADIO_PORT=7865
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5003
    - VTN_PORT=8083
    - VTN_SELF_HOST=http://172.18.0.5
    - LAYER=2
    - CONNECT_VTN_URL=http://172.18.0.3:8081/0/0/OpenADR2/Simple/2.0b
    ports:
    - '8083:8083'
    - '7865:7865'
    - '5003:5003'
    networks:
      my_network:
        ipv4_address: 172.18.0.5
    depends_on:
      '0_0':
        condition: service_healthy
    expose:
    - 8083
    - 5003
  '0_1':
    build:
      context: .
      dockerfile: ./src/docker/middle_node/Dockerfile
    container_name: 0_1_container
    environment:
    - VTN_NAME=vtn_0_1
    - VTN_URL=http://localhost:8084/0/1/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/1/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_1
    - GRADIO_PORT=7866
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5004
    - VTN_PORT=8084
    - VTN_SELF_HOST=http://172.18.0.6
    - LAYER=1
    - CONNECT_VTN_URL=http://172.18.0.2:8080/0/OpenADR2/Simple/2.0b
    ports:
    - '8084:8084'
    - '7866:7866'
    - '5004:5004'
    networks:
      my_network:
        ipv4_address: 172.18.0.6
    depends_on:
      '0':
        condition: service_healthy
    expose:
    - 8084
    - 5004
    healthcheck:
      test: 'curl -f -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:8084/0/1/OpenADR2/Simple/2.0b
        | grep 404 || exit 1'
      interval: 30s
      timeout: 10s
      retries: 10
  '0_1_0':
    build:
      context: .
      dockerfile: ./src/docker/bottom_node/Dockerfile
    container_name: 0_1_0_container
    environment:
    - VTN_NAME=vtn_0_1_0
    - VTN_URL=http://localhost:8085/0/1/0/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/1/0/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_1_0
    - GRADIO_PORT=7867
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5005
    - VTN_PORT=8085
    - VTN_SELF_HOST=http://172.18.0.7
    - LAYER=2
    - CONNECT_VTN_URL=http://172.18.0.6:8084/0/1/OpenADR2/Simple/2.0b
    ports:
    - '8085:8085'
    - '7867:7867'
    - '5005:5005'
    networks:
      my_network:
        ipv4_address: 172.18.0.7
    depends_on:
      '0_1':
        condition: service_healthy
    expose:
    - 8085
    - 5005
  '0_1_1':
    build:
      context: .
      dockerfile: ./src/docker/bottom_node/Dockerfile
    container_name: 0_1_1_container
    environment:
    - VTN_NAME=vtn_0_1_1
    - VTN_URL=http://localhost:8086/0/1/1/OpenADR2/Simple/2.0b
    - VTN_PATH_PREFIX=/0/1/1/OpenADR2/Simple/2.0b
    - VEN_NAME=ven_0_1_1
    - GRADIO_PORT=7868
    - GRADIO_SERVER_NAME=0.0.0.0
    - REST_API_PORT=5006
    - VTN_PORT=8086
    - VTN_SELF_HOST=http://172.18.0.8
    - LAYER=2
    - CONNECT_VTN_URL=http://172.18.0.6:8084/0/1/OpenADR2/Simple/2.0b
    ports:
    - '8086:8086'
    - '7868:7868'
    - '5006:5006'
    networks:
      my_network:
        ipv4_address: 172.18.0.8
    depends_on:
      '0_1':
        condition: service_healthy
    expose:
    - 8086
    - 5006
  node_dashboard:
    build:
      context: .
      dockerfile: ./src/docker/node_dashboard/Dockerfile
    container_name: node_dashboard
    ports:
    - '7860:7860'
    networks:
      my_network:
        ipv4_address: 172.18.0.9
    environment:
    - NODE_GRADIO_PORT=7860
networks:
  my_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
