services:
  '0':
    build:
      context: .
      dockerfile: Dockerfile_first
    container_name: 0_container
    environment:
    - VTN_NAME=vtn_0
    - VEN_NAME=ven_0
    - PATH_PREFIX=/0
    ports:
    - "8080:80"
version: '3.8'
